drop table usr if exists;

drop table citizenship if exists;

drop table doc_concrete if exists;

drop table doc_type if exists;

drop table office if exists;

drop table organization if exists;

drop sequence if exists hibernate_sequence;


create table citizenship
(
  citizenship_code bigint       not null,
  citizenship_name varchar(255) not null,
  primary key (citizenship_code)
);
create table doc_concrete
(
  doc_number varchar(255) not null,
  doc_date   date         not null,
  doc_code   bigint       not null,
  primary key (doc_number)
);
create table doc_type
(
  doc_code bigint       not null,
  doc_name varchar(255) not null,
  primary key (doc_code)
);
create table office
(
  id              bigint generated by default as identity,
  adress          varchar(255),
  is_active       boolean not null,
  name            varchar(255),
  phone           varchar(255),
  version         bigint  not null,
  organization_id bigint  not null,
  primary key (id)
);
create table organization
(
  id        bigint generated by default as identity,
  adress    varchar(255) not null,
  full_name varchar(255) not null,
  inn       varchar(255) not null,
  is_active boolean      not null,
  kpp       varchar(255) not null,
  name      varchar(255) not null,
  phone     varchar(255),
  version   bigint       not null,
  primary key (id)
);
create table usr
(
  id                      bigint generated by default as identity,
  first_name              varchar(255) not null,
  is_identified           boolean      not null,
  middle_name             varchar(255),
  phone                   varchar(255),
  position                varchar(255) not null,
  second_name             varchar(255),
  version                 bigint       not null,
  citizenship_code        bigint,
  doc_concrete_doc_number varchar(255),
  office_id               bigint       not null,
  primary key (id)
);
create index IX_citizenship_citizenshipCode on citizenship (citizenship_code);
create index IX_doc_concrete_docType on doc_concrete (doc_code);
create index IX_doc_type_docCode on doc_type (doc_code);
create index IX_office_organization on office (organization_id);
create index IX_office_name on office (name);
create index UX_office_phone on office (phone);
create index IX_office_isActive on office (is_active);
create index IX_organization_name on organization (name);
create index UX_organization_inn on organization (inn);
create index IX_organization_isActive on organization (is_active);
create index IX_usr_office on usr (office_id);
create index IX_usr_firstName on usr (first_name);
create index IX_usr_secondName on usr (second_name);
create index IX_usr_middleName on usr (middle_name);
create index IX_usr_position on usr (position);
create index IX_usr_citizenship on usr (citizenship_code);
alter table doc_concrete
  add constraint FKr0cxbah1iu5lyhkntnquq1un0 foreign key (doc_code) references doc_type;
alter table office
  add constraint FKaa75do6pm855upok2c8g2rhbk foreign key (organization_id) references organization;
alter table usr
  add constraint FKfdceh039sg6imvqdv0eo5c5jn foreign key (citizenship_code) references citizenship;
alter table usr
  add constraint FKkc4ksj1up1d8oxp9bu8ey19xv foreign key (doc_concrete_doc_number) references doc_concrete;
alter table usr
  add constraint FK17kfclc8qt8kn3n4hg8hk58nm foreign key (office_id) references office
